{ lib, config, pkgs, self, ... }:

with lib;

let
  cfg  = config.services.wings;
  pkg  = pkgs.callPackage (self + /pkgs/wings.nix) {};
in {
  options.services.wings = {
    enable = mkEnableOption "Pterodactyl Wings daemon";

    configFile = mkOption {
      type    = types.nullOr types.path;
      default = null;
      example = "/run/agenix/wings-config";
      description = mdDoc ''
        Path to the Wings `config.yml`.
        Typically generated by the Pterodactyl panel — copy it to the node
        and then reference it here (or manage it with agenix).
      '';
    };

    package = mkOption {
      type    = types.package;
      default = pkg;
      description = mdDoc "The Wings binary package to use.";
    };

    openFirewall = mkOption {
      type    = types.bool;
      default = true;
      description = mdDoc ''
        Open the ports Wings needs:
        - 8080 (HTTP API / SFTP port negotiation)
        - 2022 (SFTP)
      '';
    };
  };

  config = mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.configFile != null;
        message   = "services.wings.configFile must be set to the path of your Wings config.yml.";
      }
    ];

    # Wings runs game servers inside Docker containers.
    virtualisation.docker = {
      enable        = true;
      autoPrune.enable = true;
    };

    # Symlink the config into /etc so Wings can always find it,
    # but the actual file can live anywhere (e.g. /run/agenix/…).
    environment.etc."pterodactyl/config.yml" = {
      source = cfg.configFile;
      mode   = "0600";
    };

    environment.systemPackages = [ cfg.package ];

    systemd.services.wings = {
      description = "Pterodactyl Wings";
      after        = [ "docker.service" "network-online.target" ];
      requires     = [ "docker.service" ];
      wants        = [ "network-online.target" ];
      wantedBy     = [ "multi-user.target" ];

      unitConfig = {
        StartLimitIntervalSec = 180;
        StartLimitBurst       = 30;
      };

      serviceConfig = {
        User             = "root"; # Wings needs root to manage Docker + cgroups
        WorkingDirectory = "/var/lib/wings";
        RuntimeDirectory = "wings";
        LimitNOFILE      = 4096;
        ExecStartPre     = "${pkgs.coreutils}/bin/mkdir -p /var/lib/wings";
        ExecStart        = "${cfg.package}/bin/wings --config /etc/pterodactyl/config.yml";
        Restart          = "on-failure";
        RestartSec       = "5s";
      };
    };

    networking.firewall.allowedTCPPorts = mkIf cfg.openFirewall [ 8080 2022 ];
  };
}
